_format_version: "2.1"
_transform: true

services:
  - name: test
<<<<<<< HEAD
    url: https://httpbin.org
=======
    url: https://mockbin.org
>>>>>>> b24d1d77c78659ffe1fd7978439dcc0a8a8428bd
    routes:
      - name: test-route
        paths:
          - /demo

    plugins:
      - name: authopa
        enabled: true
        config:
          redis:
            host: "redis"
            port: 6379
            ttl: 10
          postgres:
            user: "postgres"
            password: "password"
            host: "postgres"
            port: 5432
  