version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - defaultnw
    restart: unless-stopped
  
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    networks:
      - defaultnw
    restart: unless-stopped

  kong-demo:
    privileged: true
    user: root
    build: .
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_DATABASE=off
      - KONG_LOG_LEVEL=info
      - KONG_PLUGINS=bundled,authopa
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      # - KONG_LICENSE_DATA= #insertlicensedata
    container_name: kong-demo
    networks:
      - defaultnw

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    networks:
      - defaultnw
    environment:
      - OPA_LOG_TIMESTAMP_FORMAT="2006-01-02T15:04:05.999999999Z07:00"
    command:
      - "run"
      - "--server"
    volumes:
      - ./authopa.rego:/policies/authopa.rego

networks:
  defaultnw:
    driver: bridge

volumes:
    postgres:
    pgadmin:




