version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - defaultnw
    restart: unless-stopped
  
<<<<<<< HEAD
=======
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - defaultnw
    restart: unless-stopped

>>>>>>> b24d1d77c78659ffe1fd7978439dcc0a8a8428bd
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    networks:
      - defaultnw
    restart: unless-stopped
<<<<<<< HEAD
=======
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=redis
    ports:
      - 8081:8081
    networks:
      - defaultnw
    depends_on:
      - redis

## kong
>>>>>>> b24d1d77c78659ffe1fd7978439dcc0a8a8428bd

  kong-demo:
    privileged: true
    user: root
    build: .
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_DATABASE=off
<<<<<<< HEAD
      - KONG_LOG_LEVEL=info
      - KONG_PLUGINS=bundled,authopa
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      # - KONG_LICENSE_DATA= #insertlicensedata
    container_name: kong-demo
    networks:
      - defaultnw
=======
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled,authopa
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA= #insertLicence
    container_name: kong-demo
    networks:
      - defaultnw
## OPA
>>>>>>> b24d1d77c78659ffe1fd7978439dcc0a8a8428bd

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    networks:
      - defaultnw
    environment:
      - OPA_LOG_TIMESTAMP_FORMAT="2006-01-02T15:04:05.999999999Z07:00"
    command:
      - "run"
      - "--server"
<<<<<<< HEAD
=======
      # - "--config-file=/opa-conf.yaml"    
>>>>>>> b24d1d77c78659ffe1fd7978439dcc0a8a8428bd
    volumes:
      - ./authopa.rego:/policies/authopa.rego

networks:
  defaultnw:
    driver: bridge

volumes:
    postgres:
    pgadmin:




